baseURL = "https://oaad.iceco.icu/"
defaultContentLanguage = "zh-cn"
languageCode = "zh-CN"
theme = "nostyleplease"
hasCJKLanguage = true
title = ""
disableKinds = ["RSS"]

[module]
  [module.hugoVersion]
    extended = true
    min      = "0.41.0"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      attribute = true

  [markup.highlight]
    anchorLineNos      = false
    codeFences         = true
    guessSyntax        = false
    hl_Lines           = ''
    hl_inline          = false
    lineAnchors        = ''
    lineNoStart        = 1
    lineNos            = false
    lineNumbersInTable = true
    noClasses          = true
    noHl               = false
    style              = 'rrt'
    tabWidth           = 4

  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = false

[params]
  enableCarousel = true
  description = 'WELCOME(´▽`ʃ♡ƪ)'
  [params.theme_config]
    show_description  = true
    appearance        = "dark"
    back_home_text    = ".."
    date_format       = "2006-01-02"
    isListGroupByDate = true
    isShowFooter      = true
